version: "3"

services:
  python:
      hostname: python
      restart: always
      container_name: python
      image: local-python-3.11
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        TZ: "Asia/Shanghai"
      ports:
        - "7860:7860"
      volumes:
        - ./chatbot.py:/app/chatbot.py
      command: python chatbot.py